 ;;;Exercise 2.12
(load "ex2-8.scm")
(define (make-center-width c w)
    (make-interval (- c w) (+ c w)))
(define (center i)
    (/ (+ (lower-bound i) (upper-bound i)) 2))
(define (width i)
    (/ (- (upper-bound i) (lower-bound i)) 2))
(define (make-center-percent c p)
    (make-interval (- c (* c (/ p 100.0))) (+ c (* c (/ p 100.0)))))
(define (percent i)
    (/ (* 100 (/ (- (upper-bound i) (lower-bound i)) (center i))) 2))
;(make-center-percent 5 5)
;(percent (make-center-percent 5 5))
