;;; Exercise 2.1
(load "gcd.scm")
(define (make-rat n d) 
    (let ((g (gcd n d)))
        (if (> (/ n d) 0)
            (cons (/ n g) (/ d g))
            (cons (- (abs (/ n g))) (abs (/ d g))))))
(define (numer x) (car x))
(define (denom x) (cdr x))
(define (print-rat x)
    (newline)
    (display (numer x))
    (display "/")
    (display (denom x)))
(define (add-rat x y)
    (make-rat (+ (* (numer x) (denom y))
                 (* (numer y) (denom x)))
              (* (denom x) (denom y))))
(define (sub-rat x y)
    (make-rat (- (* (numer x) (denom y))
                 (* (numer y) (denom x)))
              (* (denom x) (denom y))))
(define (mul-rat x y)
    (make-rat  (* (numer x) (denom y))
               (* (numer y) (denom x))))
(define (div-rat x y)
    (make-rat (* (numer x) (denom y))
              (* (denom x) (numer y))))
(define (equal-rat? x y)
    (= (* (numer x) (denom y))
       (* (numer y) (denom x))))
(define test1 (make-rat 2 4))
(print-rat test1)
(define test2 (make-rat 2 -4))
(print-rat test2)
(define test3 (make-rat -2 4))
(print-rat test3)
(define test4 (make-rat -2 -4))
(print-rat test4)
