;; Exercise 3.7
(define (make-account balance pwd)
  (define (withdraw amount)
    (if (>= balance amount)
      (begin (set! balance
	       (- balance amount))
	     balance)
      "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch m1 m2)
    (if (eq? m1 pwd)
    	(cond ((eq? m2 'withdraw) withdraw)
	  	((eq? m2 'deposit) deposit)
	  	(else (error "Unknown request: MAKE-ACCOUNT" m2)))
	(lambda (m) "Incorrect password")))
  dispatch)
(define (make-joint acc pwd1 pwd2)
    (define (dispatch m1 m2)
        (if (eq? m1 pwd2)
            (cond ((eq? m2 'withdraw) (acc pwd1 'withdraw))
                  ((eq? m2 'deposit) (acc pwd1 'deposit))
                  (else (error "Unknown request: " m2)))
            (lambda (m) "Incorrect password")))
dispatch)

;; test
(define peter-acc (make-account 100 'open-sesame))
(define paul-acc (make-joint peter-acc 'open-sesame 'rosebud))
((paul-acc 'rosebud 'withdraw) 10)
((paul-acc 'rosbud 'withdraw) 10)
((peter-acc 'rosebud 'withdraw) 10)
((peter-acc 'open-sesame 'withdraw) 10)
